image: node:10.14.1


clone:
    depth: full

pipelines:
    branches:
        master:
            - step:
                name: Testing App
                caches:
                    - node
                script:
                    - rm -rf package-lock.json
                    - rm -rf node_modules
                    - npm install --production --quiet
                    - npm run test
            - step:
                name: Move To Production
                deployment: Production
                caches:
                    - node
                script:
                    - npm install
                    - npm run build
                    - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master:master